name: Documentation

on:
  push:
    tags:
      - v*

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Intstall dependencies
        run: sudo apt-get install -y git
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          working-directory: doc/
        env:
          DOXYGEN_PROJECT_NUMBER: "${{ github.ref_name }}"
      - run: rm doc/.gitignore
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pages
          FOLDER: doc/html/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
